; ============================================================
; Atari 2600 Music Data
; Song: Shadows Gather — Forest of Mysteries OST
; Generated by Atari Sound Editor
; ============================================================

; NOTE CODE FORMAT: [driverCode(3 bits)][frequency(5 bits)]
; Driver codes:
;   000 = Square  (AUDC=4)    001 = Bass    (AUDC=6)
;   010 = Pitfall (AUDC=7)    011 = Noise   (AUDC=8)
;   100 = Buzz    (AUDC=15)   101 = Lead    (AUDC=12)
;   110 = Saw     (AUDC=1)    111 = Engine  (AUDC=3)
;   $00 = Rest (silence)

MUSIC_TEMPO     = 7   ; frames per step (NTSC 60fps)
MUSIC_NUM_PATS  = 9

; ============================================================
; PATTERN DATA
; ============================================================

; Pattern: Into Darkness (16 steps)
Shadows_Gather_Into_Darkness_len = 16

Shadows_Gather_Into_Darkness_v0_notes:
    .byte $CA, $00, $00, $00, $CC, $00, $00, $00, $CA, $00, $00, $9E, $CC, $00, $00, $00  ; voice 0 note codes

Shadows_Gather_Into_Darkness_v0_vols:
    .byte $07, $00, $00, $00, $07, $00, $00, $00, $07, $00, $00, $08, $07, $00, $00, $00  ; voice 0 volumes

Shadows_Gather_Into_Darkness_v1_notes:
    .byte $BE, $00, $BC, $00, $B9, $00, $BC, $00, $BE, $00, $B5, $00, $00, $B9, $00, $BE  ; voice 1 note codes

Shadows_Gather_Into_Darkness_v1_vols:
    .byte $09, $00, $09, $00, $09, $00, $09, $00, $09, $00, $09, $00, $00, $08, $00, $07  ; voice 1 volumes

; Pattern: Omen (16 steps)
Shadows_Gather_Omen_len = 16

Shadows_Gather_Omen_v0_notes:
    .byte $CC, $00, $00, $9E, $DE, $00, $00, $00, $CC, $00, $9E, $00, $CA, $00, $00, $9E  ; voice 0 note codes

Shadows_Gather_Omen_v0_vols:
    .byte $07, $00, $00, $08, $06, $00, $00, $00, $07, $00, $08, $00, $07, $00, $00, $07  ; voice 0 volumes

Shadows_Gather_Omen_v1_notes:
    .byte $B5, $00, $B6, $00, $B9, $00, $00, $BE, $00, $B9, $BC, $00, $BE, $00, $00, $00  ; voice 1 note codes

Shadows_Gather_Omen_v1_vols:
    .byte $09, $00, $09, $00, $09, $00, $00, $09, $00, $09, $09, $00, $09, $00, $00, $00  ; voice 1 volumes

; Pattern: Forest Beckons (16 steps)
Shadows_Gather_Forest_Beckons_len = 16

Shadows_Gather_Forest_Beckons_v0_notes:
    .byte $CA, $00, $00, $00, $00, $CC, $00, $00, $9E, $00, $CA, $00, $00, $00, $00, $9E  ; voice 0 note codes

Shadows_Gather_Forest_Beckons_v0_vols:
    .byte $07, $00, $00, $00, $00, $06, $00, $00, $08, $00, $07, $00, $00, $00, $00, $07  ; voice 0 volumes

Shadows_Gather_Forest_Beckons_v1_notes:
    .byte $00, $1C, $00, $00, $B9, $00, $00, $BC, $00, $00, $BE, $00, $B5, $00, $00, $00  ; voice 1 note codes

Shadows_Gather_Forest_Beckons_v1_vols:
    .byte $00, $09, $00, $00, $09, $00, $00, $09, $00, $00, $09, $00, $08, $00, $00, $00  ; voice 1 volumes

; ============================================================
; ARRANGEMENT TABLE
; Each entry = 4 pointers: v0_notes, v0_vols, v1_notes, v1_vols
; ============================================================

Shadows_Gather_arrangement:
    ; arrangement[0] = Into Darkness
    .word Shadows_Gather_Into_Darkness_v0_notes
    .word Shadows_Gather_Into_Darkness_v0_vols
    .word Shadows_Gather_Into_Darkness_v1_notes
    .word Shadows_Gather_Into_Darkness_v1_vols
    .byte Shadows_Gather_Into_Darkness_len
    ; arrangement[1] = Into Darkness
    .word Shadows_Gather_Into_Darkness_v0_notes
    .word Shadows_Gather_Into_Darkness_v0_vols
    .word Shadows_Gather_Into_Darkness_v1_notes
    .word Shadows_Gather_Into_Darkness_v1_vols
    .byte Shadows_Gather_Into_Darkness_len
    ; arrangement[2] = Omen
    .word Shadows_Gather_Omen_v0_notes
    .word Shadows_Gather_Omen_v0_vols
    .word Shadows_Gather_Omen_v1_notes
    .word Shadows_Gather_Omen_v1_vols
    .byte Shadows_Gather_Omen_len
    ; arrangement[3] = Into Darkness
    .word Shadows_Gather_Into_Darkness_v0_notes
    .word Shadows_Gather_Into_Darkness_v0_vols
    .word Shadows_Gather_Into_Darkness_v1_notes
    .word Shadows_Gather_Into_Darkness_v1_vols
    .byte Shadows_Gather_Into_Darkness_len
    ; arrangement[4] = Forest Beckons
    .word Shadows_Gather_Forest_Beckons_v0_notes
    .word Shadows_Gather_Forest_Beckons_v0_vols
    .word Shadows_Gather_Forest_Beckons_v1_notes
    .word Shadows_Gather_Forest_Beckons_v1_vols
    .byte Shadows_Gather_Forest_Beckons_len
    ; arrangement[5] = Into Darkness
    .word Shadows_Gather_Into_Darkness_v0_notes
    .word Shadows_Gather_Into_Darkness_v0_vols
    .word Shadows_Gather_Into_Darkness_v1_notes
    .word Shadows_Gather_Into_Darkness_v1_vols
    .byte Shadows_Gather_Into_Darkness_len
    ; arrangement[6] = Omen
    .word Shadows_Gather_Omen_v0_notes
    .word Shadows_Gather_Omen_v0_vols
    .word Shadows_Gather_Omen_v1_notes
    .word Shadows_Gather_Omen_v1_vols
    .byte Shadows_Gather_Omen_len
    ; arrangement[7] = Forest Beckons
    .word Shadows_Gather_Forest_Beckons_v0_notes
    .word Shadows_Gather_Forest_Beckons_v0_vols
    .word Shadows_Gather_Forest_Beckons_v1_notes
    .word Shadows_Gather_Forest_Beckons_v1_vols
    .byte Shadows_Gather_Forest_Beckons_len
    ; arrangement[8] = Into Darkness
    .word Shadows_Gather_Into_Darkness_v0_notes
    .word Shadows_Gather_Into_Darkness_v0_vols
    .word Shadows_Gather_Into_Darkness_v1_notes
    .word Shadows_Gather_Into_Darkness_v1_vols
    .byte Shadows_Gather_Into_Darkness_len



