import { AtariSong, MusicPattern, MusicStep } from '@/types/music';
import { encodeNoteCode } from './atariNoteTable';

/** Encode a step as a note code byte (0 = rest/silence) */
function stepToNoteCode(step: MusicStep | null): number {
  if (!step || step.audv === 0) return 0x00;
  return encodeNoteCode(step.audc, step.audf);
}

function toHex(v: number): string {
  return `$${v.toString(16).padStart(2, '0').toUpperCase()}`;
}

function byteRow(values: number[], label: string): string {
  const hex = values.map(toHex).join(', ');
  return `    .byte ${hex}  ; ${label}`;
}

function safeName(s: string): string {
  return s
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .replace(/^([0-9])/, '_$1');
}

export function exportSongToAsm(song: AtariSong): void {
  const name = safeName(song.name || 'song');
  const lines: string[] = [];

  lines.push(
    `; ============================================================`,
    `; Atari 2600 Music Data`,
    `; Song: ${song.name}${song.artist ? ` — ${song.artist}` : ''}`,
    `; Generated by Atari Sound Editor`,
    `; ============================================================`,
    ``,
    `; NOTE CODE FORMAT: [driverCode(3 bits)][frequency(5 bits)]`,
    `; Driver codes:`,
    `;   000 = Square  (AUDC=4)    001 = Bass    (AUDC=6)`,
    `;   010 = Pitfall (AUDC=7)    011 = Noise   (AUDC=8)`,
    `;   100 = Buzz    (AUDC=15)   101 = Lead    (AUDC=12)`,
    `;   110 = Saw     (AUDC=1)    111 = Engine  (AUDC=3)`,
    `;   $00 = Rest (silence)`,
    ``,
    `MUSIC_TEMPO     = ${song.tempo}   ; frames per step (NTSC 60fps)`,
    `MUSIC_NUM_PATS  = ${song.arrangement.length}`,
    ``,
  );

  // ── Pattern data ──────────────────────────────────────────────────────────
  const patternById = new Map(song.patterns.map(p => [p.id, p]));

  lines.push(`; ============================================================`);
  lines.push(`; PATTERN DATA`);
  lines.push(`; ============================================================`);

  song.patterns.forEach(pattern => {
    const pname = safeName(pattern.name);
    const v0notes = pattern.voice0.map(stepToNoteCode);
    const v1notes = pattern.voice1.map(stepToNoteCode);
    const v0vols  = pattern.voice0.map(s => (s?.audv ?? 0));
    const v1vols  = pattern.voice1.map(s => (s?.audv ?? 0));

    lines.push(
      ``,
      `; Pattern: ${pattern.name} (${pattern.length} steps)`,
      `${name}_${pname}_len = ${pattern.length}`,
      ``,
      `${name}_${pname}_v0_notes:`,
      byteRow(v0notes, 'voice 0 note codes'),
      ``,
      `${name}_${pname}_v0_vols:`,
      byteRow(v0vols, 'voice 0 volumes'),
      ``,
      `${name}_${pname}_v1_notes:`,
      byteRow(v1notes, 'voice 1 note codes'),
      ``,
      `${name}_${pname}_v1_vols:`,
      byteRow(v1vols, 'voice 1 volumes'),
    );
  });

  // ── Arrangement table ─────────────────────────────────────────────────────
  lines.push(
    ``,
    `; ============================================================`,
    `; ARRANGEMENT TABLE`,
    `; Each entry = 9 bytes: v0_notes, v0_vols, v1_notes, v1_vols (words) + length (byte)`,
    `; ============================================================`,
    ``,
    `${name}_arrangement:`,
  );

  song.arrangement.forEach((pid, idx) => {
    const pattern = patternById.get(pid);
    if (!pattern) return;
    const pname = safeName(pattern.name);
    lines.push(
      `    ; arrangement[${idx}] = ${pattern.name}`,
      `    .word ${name}_${pname}_v0_notes`,
      `    .word ${name}_${pname}_v0_vols`,
      `    .word ${name}_${pname}_v1_notes`,
      `    .word ${name}_${pname}_v1_vols`,
      `    .byte ${name}_${pname}_len`,
    );
  });

  // ── Music engine ───────────────────────────────────────────────────────────
  lines.push(
    ``,
    `; ============================================================`,
    `; MUSIC ENGINE`,
    `; ============================================================`,
    `; Required zero-page RAM:`,
    `;   MUS_FRAME   - frame countdown (1 byte)`,
    `;   MUS_STEP    - step within pattern (1 byte)`,
    `;   MUS_PAT_IDX - arrangement index (1 byte)`,
    `;   MUS_PLAYING - 0=stopped, 1=playing (1 byte)`,
    `;   MUS_ARR_OFF - saved arrangement byte offset (1 byte)`,
    `;   MUS_PTR     - temp zero-page pointer (2 bytes)`,
    `; Required RAM addresses: AUDV0, AUDV1, AUDF0, AUDF1, AUDC0, AUDC1`,
    `; ============================================================`,
    `;`,
    `; Arrangement entry layout (9 bytes each):`,
    `;   +0,+1  .word  voice 0 note codes ptr`,
    `;   +2,+3  .word  voice 0 volumes ptr`,
    `;   +4,+5  .word  voice 1 note codes ptr`,
    `;   +6,+7  .word  voice 1 volumes ptr`,
    `;   +8     .byte  pattern length`,
    `; ============================================================`,
    ``,
    `; Driver code → TIA AUDC lookup table`,
    `musCtrlTable:`,
    `    .byte 4, 6, 7, 8, 15, 12, 1, 3`,
    ``,
    `; ── MUSIC_INIT ─────────────────────────────────────────────────────────`,
    `; Call once at startup to begin playback from the beginning`,
    `MUSIC_INIT:`,
    `    lda #MUSIC_TEMPO`,
    `    sta MUS_FRAME`,
    `    lda #0`,
    `    sta MUS_STEP`,
    `    sta MUS_PAT_IDX`,
    `    lda #1`,
    `    sta MUS_PLAYING`,
    `    rts`,
    ``,
    `; ── MUSIC_STOP ─────────────────────────────────────────────────────────`,
    `MUSIC_STOP:`,
    `    lda #0`,
    `    sta MUS_PLAYING`,
    `    sta AUDV0`,
    `    sta AUDV1`,
    `    rts`,
    ``,
    `; ── MUSIC_UPDATE ───────────────────────────────────────────────────────`,
    `; Call once per frame (during vertical blank recommended)`,
    `MUSIC_UPDATE:`,
    `    lda MUS_PLAYING`,
    `    beq .musExit        ; not playing → return (branch target is nearby)`,
    `    dec MUS_FRAME`,
    `    beq .musStep        ; frame expired → do step (invert: fall through = not done)`,
    `.musExit:`,
    `    rts`,
    ``,
    `.musStep:`,
    `    lda #MUSIC_TEMPO`,
    `    sta MUS_FRAME`,
    ``,
    `    ; Calculate arrangement entry byte offset (9 bytes per entry)`,
    `    lda MUS_PAT_IDX`,
    `    asl             ; *2`,
    `    asl             ; *4`,
    `    asl             ; *8`,
    `    clc`,
    `    adc MUS_PAT_IDX ; +idx = *9`,
    `    tax`,
    `    stx MUS_ARR_OFF ; save offset — AUDC table lookup will clobber X`,
    ``,
    `    ; Get current step`,
    `    ldy MUS_STEP`,
    ``,
    `    ; ── Voice 0 note ─────────────────────────────`,
    `    lda ${name}_arrangement,x   ; v0 notes ptr lo`,
    `    sta MUS_PTR`,
    `    lda ${name}_arrangement+1,x ; v0 notes ptr hi`,
    `    sta MUS_PTR+1`,
    `    lda (MUS_PTR),y             ; load note code`,
    `    beq .v0Silence`,
    `    pha                         ; save note code`,
    `    lsr`,
    `    lsr`,
    `    lsr`,
    `    lsr`,
    `    lsr                         ; driver code (0-7)`,
    `    tax`,
    `    lda musCtrlTable,x`,
    `    sta AUDC0`,
    `    pla                         ; restore note code`,
    `    and #%00011111`,
    `    sta AUDF0`,
    `    ldx MUS_ARR_OFF             ; restore arrangement offset`,
    `    lda ${name}_arrangement+2,x ; v0 vols ptr lo`,
    `    sta MUS_PTR`,
    `    lda ${name}_arrangement+3,x ; v0 vols ptr hi`,
    `    sta MUS_PTR+1`,
    `    lda (MUS_PTR),y`,
    `    sta AUDV0`,
    `    jmp .v1Note`,
    `.v0Silence:`,
    `    lda #0`,
    `    sta AUDV0`,
    ``,
    `    ; ── Voice 1 note ─────────────────────────────`,
    `.v1Note:`,
    `    ldx MUS_ARR_OFF             ; restore arrangement offset`,
    `    lda ${name}_arrangement+4,x ; v1 notes ptr lo`,
    `    sta MUS_PTR`,
    `    lda ${name}_arrangement+5,x ; v1 notes ptr hi`,
    `    sta MUS_PTR+1`,
    `    lda (MUS_PTR),y             ; load note code`,
    `    beq .v1Silence`,
    `    pha                         ; save note code`,
    `    lsr`,
    `    lsr`,
    `    lsr`,
    `    lsr`,
    `    lsr                         ; driver code (0-7)`,
    `    tax`,
    `    lda musCtrlTable,x`,
    `    sta AUDC1`,
    `    pla                         ; restore note code`,
    `    and #%00011111`,
    `    sta AUDF1`,
    `    ldx MUS_ARR_OFF             ; restore arrangement offset`,
    `    lda ${name}_arrangement+6,x ; v1 vols ptr lo`,
    `    sta MUS_PTR`,
    `    lda ${name}_arrangement+7,x ; v1 vols ptr hi`,
    `    sta MUS_PTR+1`,
    `    lda (MUS_PTR),y`,
    `    sta AUDV1`,
    `    jmp .advanceStep`,
    `.v1Silence:`,
    `    lda #0`,
    `    sta AUDV1`,
    ``,
    `    ; ── Advance step ──────────────────────────────`,
    `.advanceStep:`,
    `    ldx MUS_ARR_OFF`,
    `    inc MUS_STEP`,
    `    lda ${name}_arrangement+8,x ; pattern length`,
    `    cmp MUS_STEP`,
    `    bne .musEnd`,
    `    lda #0`,
    `    sta MUS_STEP`,
    `    inc MUS_PAT_IDX`,
    `    lda MUS_PAT_IDX`,
    `    cmp #MUSIC_NUM_PATS`,
    `    bne .musEnd`,
    `    lda #0`,
    `    sta MUS_PAT_IDX`,
    `.musEnd:`,
    `    rts`,
  );

  const asm = lines.join('\n');
  const blob = new Blob([asm], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${safeName(song.name || 'song').toLowerCase()}-music.asm`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Save a song as a JSON file */
export function saveSong(song: AtariSong): void {
  const json = JSON.stringify(song, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${safeName(song.name || 'song').toLowerCase()}-music.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Load a song from a JSON file, returns null on parse failure */
export function loadSong(file: File): Promise<AtariSong | null> {
  return new Promise(resolve => {
    const reader = new FileReader();
    reader.onload = e => {
      try {
        const song = JSON.parse(e.target?.result as string) as AtariSong;
        resolve(song);
      } catch {
        resolve(null);
      }
    };
    reader.onerror = () => resolve(null);
    reader.readAsText(file);
  });
}
